First draft of the d20 Engine (#66)
* Initial commit

* Builds together a good chunk of the character data calculator

* Halfway between trying smoething new

* Delete old crap

* Yep more work

* Adds test script and other crap.  Fixes up the d20 engine calculation

* Incorporates gear into the stat calculations

* Adds equipment armor and shield bonus to ac

* Bit o' refactoring

* Refactoring

* More refactoring!

* getting ready to cut over aggregate breakdowns

* Reorganize the stat matrix to flatten on the adjustments

* Extract constants

* Refacot

* Got saves working

* Save breakdowns, class skills

* Total save accumulation

* Skill mod breakdown tests

* Carrying capacity, current inventory weight

* Move stuff around

* Ugh so complicated

diff --git a/bin/runtests b/bin/runtests
--- a/bin/runtests
+++ b/bin/runtests
@@ -1,11 +1,19 @@
 #!/bin/bash
 #
-# This script rsyncs code on local machines to the webserver.
-# This project will not work properly unless you setup your ssh config file
+# This script wraps tests to decouple our application from mocha and allows us to organize our directory
+# better.  Also allows us to run different mutually exclusive testing environments.
 #
-set -e
+# Intentionally dont use set -e because the test runners can stop one another
+# if there are failures.
 
 # Get to project root
 cd "$(dirname "$0")/.."
 
-node_modules/mocha/bin/mocha
+#echo "Rebuilding database..."
+#npm run mysql_import
+
+echo "Running default tests"
+./tests/default/run --reporter dot
+
+#echo "Running react tests"
+#./tests/react/run --reporter dot
